version: '3.3'
services:

  mariadb:
    image: mariadb:11.1.2
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: exampledb
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  tomcat1:
    image: tomcat:10.1.9-jdk17
    container_name: tomcat1
    ports:
      - "8081:8081"

    volumes:
      - ./sample.war:/usr/local/tomcat/webapps/sample.war

  tomcat2:
    image: tomcat:10.1.9-jdk17
    container_name: tomcat2
    ports:
      - "8082:8082"
    volumes:
      - ./sample.war:/usr/local/tomcat/webapps/sample.war

  cloudbeaver:
    image: dbeaver/cloudbeaver:23.3.0
    container_name: cloudbeaver
    ports:
      - "8978:8978"
  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8090:8090"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  mariadb_data: